services:
  ####################################
  ### Dispatcher
  ####################################
  paramiko:
    container_name: paramiko
    build: ../dispatcher/paramiko
    depends_on:
      - launcher
      - heralding
      - cowrie
    ports:
      - "22:22"
    env_file:
      - ../.env
    volumes:
      - ${SPRING_DATA_PATH}/paramiko:/var/log/paramiko
    restart: always

  ####################################
  ### Launcher
  ####################################
  launcher:
    container_name: launcher
    build: ../launcher
    env_file:
      - ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${SPRING_DATA_PATH}:/data
    restart: always

  ####################################
  ### Layers
  ####################################

  ##############
  ## Active
  ##############

  ### HTTP, SSH ###
  heralding:
    container_name: heralding
    image: ghcr.io/telekom-security/heralding:24.04.1
    volumes:
      - ${SPRING_DATA_PATH}/heralding:/var/log/heralding
    tmpfs:
      - /tmp/heralding:uid=2000,gid=2000
    restart: always
    read_only: true

  ##############
  ## Passive
  ##############

  ### SSH ###
  cowrie:
    container_name: cowrie
    image: cowrie/cowrie
    volumes:
      - ../layers/core/config/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt
      - ${SPRING_DATA_PATH}/cowrie:/cowrie/cowrie-git/var/log/cowrie
    environment:
      - PYTHONUNBUFFERED=1
      - COWRIE_TTYLOG_ENABLED=yes
    restart: always
